/*
 * Wallet
 * Integrate Neem Wallet APIs into your ecosystem to provide your customer the ability to create wallets, set up a financial PIN, ability to manage their wallets and have on request visibility over their balances.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DepositWithdrawApi
 */
@Ignore
public class DepositWithdrawApiTest {

    private final DepositWithdrawApi api = new DepositWithdrawApi();

    
    /**
     * Cash In
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashInTest() {
        String walletId = null;
        String xNeemPartnerId = null;
        String xNeemID = null;
        String contentType = null;
        Object body = null;
        Object response = api.cashIn(walletId, xNeemPartnerId, xNeemID, contentType, body);

        // TODO: test validations
    }
    
    /**
     * Cash In Inquiry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashInInquiryTest() {
        String walletId = null;
        String endToEndIdentification = null;
        String amount = null;
        String currency = null;
        List<Object> extendedProperties = null;
        Object response = api.cashInInquiry(walletId, endToEndIdentification, amount, currency, extendedProperties);

        // TODO: test validations
    }
    
    /**
     * Cash Out
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashOutTest() {
        String walletId = null;
        String xNeemPartnerId = null;
        String xNeemNonce = null;
        String xNeemOTPCode = null;
        String contentType = null;
        Object body = null;
        Object response = api.cashOut(walletId, xNeemPartnerId, xNeemNonce, xNeemOTPCode, contentType, body);

        // TODO: test validations
    }
    
    /**
     * Cash Out Inquiry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashOutInquiryTest() {
        String walletId = null;
        String endToEndIdentification = null;
        String amount = null;
        String currency = null;
        List<Object> extendedProperties = null;
        Object response = api.cashOutInquiry(walletId, endToEndIdentification, amount, currency, extendedProperties);

        // TODO: test validations
    }
    
}
