/*
 * Wallet
 * Integrate Neem Wallet APIs into your ecosystem to provide your customer the ability to create wallets, set up a financial PIN, ability to manage their wallets and have on request visibility over their balances.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WalletServicesApi
 */
@Ignore
public class WalletServicesApiTest {

    private final WalletServicesApi api = new WalletServicesApi();

    
    /**
     * Account Lookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountLookupTest() {
        String walletId = null;
        String endToEndIdentification = null;
        String schemeName = null;
        String xNeemCNIC = null;
        String xNeemPartnerId = null;
        String contentType = null;
        Object response = api.accountLookup(walletId, endToEndIdentification, schemeName, xNeemCNIC, xNeemPartnerId, contentType);

        // TODO: test validations
    }
    
    /**
     * Account Upgrade
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountUpgradeTest() {
        String walletId = null;
        String xNeemPartnerId = null;
        String xNeemID = null;
        String contentType = null;
        Object body = null;
        Object response = api.accountUpgrade(walletId, xNeemPartnerId, xNeemID, contentType, body);

        // TODO: test validations
    }
    
    /**
     * Validate OTP
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1WalletsValidateOtpPostTest() {
        String xNeemPartnerId = null;
        String contentType = null;
        Object body = null;
        Object response = api.apiV1WalletsValidateOtpPost(xNeemPartnerId, contentType, body);

        // TODO: test validations
    }
    
    /**
     * Balance Inquiry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void balanceInquiryTest() {
        Integer walletId = null;
        String xNeemPartnerId = null;
        String xNeemID = null;
        Integer endToEndIdentification = null;
        String schemeName = null;
        List<Object> extendedProperties = null;
        Object response = api.balanceInquiry(walletId, xNeemPartnerId, xNeemID, endToEndIdentification, schemeName, extendedProperties);

        // TODO: test validations
    }
    
    /**
     * Change MPIN
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changeMpinTest() {
        String walletId = null;
        String xNeemPartnerId = null;
        String xNeemID = null;
        String xNeemOTP = null;
        String contentType = null;
        Object body = null;
        Object response = api.changeMpin(walletId, xNeemPartnerId, xNeemID, xNeemOTP, contentType, body);

        // TODO: test validations
    }
    
    /**
     * Initiate OTP
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void initiateOtpTest() {
        String xNeemPartnerId = null;
        String contentType = null;
        Object body = null;
        Object response = api.initiateOtp(xNeemPartnerId, contentType, body);

        // TODO: test validations
    }
    
    /**
     * Transaction History
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transactionHistoryTest() {
        Integer walletId = null;
        String xNeemPartnerId = null;
        String xNeemID = null;
        Integer endToEndIdentification = null;
        Integer schemeName = null;
        String fromDate = null;
        String toDate = null;
        List<Object> extendedProperties = null;
        Object response = api.transactionHistory(walletId, xNeemPartnerId, xNeemID, endToEndIdentification, schemeName, fromDate, toDate, extendedProperties);

        // TODO: test validations
    }
    
}
